name: Teste CI

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: ${{ matrix.node-version}}        
        
    # Para instalar as dependências do package.json    
    - run: npm install
      
    # Executar os testes usando o cucumber
    - run: npm run test:run:cucumber
    
    # Gerar o relatório em html
    - run: npm run report:cucumber
    
    # Publicar relatório em html
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master    
        FOLDER: cypress/reports 